CREATE DATABASE TPCLibreriaUTN

GO
USE TPCLibreriaUTN
GO

CREATE TABLE Autores (
	IDAutor INT PRIMARY KEY IDENTITY (1,1) NOT NULL,
	Nombre NVARCHAR(50) NOT NULL,
	Apellido NVARCHAR(50) NOT NULL
)
GO

CREATE TABLE Editoriales (
	IDEditorial INT PRIMARY KEY IDENTITY (1,1) NOT NULL,
	Nombre NVARCHAR(50) NOT NULL
)
GO

CREATE TABLE Generos (
	IDGenero INT PRIMARY KEY IDENTITY (1,1) NOT NULL,
	Nombre NVARCHAR(50) NOT NULL
)
GO

CREATE TABLE Usuarios (
	IDUsuario INT PRIMARY KEY IDENTITY (1,1) NOT NULL,
	Mail NVARCHAR(50) NOT NULL,
	Clave NVARCHAR(50) NOT NULL,
	TipoUsuario INT NOT NULL,
	Eliminado BIT NOT NULL DEFAULT 0
)
GO

CREATE TABLE Clientes (
	IDCliente INT PRIMARY KEY IDENTITY (1,1) NOT NULL,
	IDUsuario INT NOT NULL FOREIGN KEY REFERENCES Usuarios(IDUsuario),
	DNI NVARCHAR(25) NOT NULL,
	Nombre NVARCHAR(50) NOT NULL,
	Apellido NVARCHAR(50) NOT NULL,
	Telefono NVARCHAR(50) NOT NULL
)
GO

CREATE TABLE Libros (
	IDLibro INT PRIMARY KEY IDENTITY (1,1) NOT NULL,
	IDAutor INT NOT NULL FOREIGN KEY REFERENCES Autores(IDAutor),
	IDGenero INT NOT NULL FOREIGN KEY REFERENCES Generos(IDGenero),
	IDEditorial INT NOT NULL FOREIGN KEY REFERENCES Editoriales(IDEditorial),
	Titulo NVARCHAR(50) NOT NULL,
	Descripcion NVARCHAR(500) NOT NULL,
	FechaPublicacion DATE NOT NULL,
	Precio MONEY NOT NULL,
	Paginas INT NOT NULL,
	Stock INT NOT NULL DEFAULT 0,
	Disponible BIT NOT NULL DEFAULT 1
)
GO

CREATE TABLE Opiniones(
    IDReseña INT PRIMARY KEY IDENTITY(1,1),
	IDLibro INT NOT NULL FOREIGN KEY REFERENCES Libros(IDLibro),
    Texto NVARCHAR(500) NOT NULL,
	Puntaje INT NOT NULL,
    Fecha DATETIME DEFAULT GETDATE()
)
GO

CREATE TABLE Portadas (
	IDPortada INT PRIMARY KEY IDENTITY (1,1) NOT NULL,
	IDLibro INT NOT NULL FOREIGN KEY REFERENCES Libros(IDLibro),
	Imagen VARCHAR(100) NOT NULL
)
GO

CREATE TABLE Deseados (
	IDDeseado INT PRIMARY KEY IDENTITY (1,1) NOT NULL,
	IDCliente INT NOT NULL FOREIGN KEY REFERENCES Clientes(IDCliente),
	IDLibro INT NOT NULL FOREIGN KEY REFERENCES Libros(IDLibro)
)
GO

CREATE TABLE Carrito (
	IDCarrito INT PRIMARY KEY IDENTITY (1,1) NOT NULL, 
	IDCliente INT NOT NULL FOREIGN KEY REFERENCES Clientes(IDCliente),
	IDLibro INT NOT NULL FOREIGN KEY REFERENCES Libros(IDLibro),
	Cantidad INT NOT NULL DEFAULT 1
)
GO

CREATE TABLE Stocks (
	IDStock INT PRIMARY KEY IDENTITY (1,1) NOT NULL,
	IDLibro INT NOT NULL FOREIGN KEY REFERENCES Libros(IDLibro),
	Cantidad INT NOT NULL
)
GO

CREATE TABLE Compras (
	IDCompra INT PRIMARY KEY IDENTITY (1,1) NOT NULL,
	FechaCompra DATETIME NOT NULL,
	IDCliente INT NOT NULL FOREIGN KEY REFERENCES Clientes(IDCliente),
	Mail NVARCHAR(50) NOT NULL,
	Nombre NVARCHAR(50) NOT NULL,
	Apellido NVARCHAR(50) NOT NULL,
	DFacturacion NVARCHAR(50) NOT NULL,
	Localidad NVARCHAR(50) NOT NULL,
	Codigo NVARCHAR(10) NOT NULL,
	Telefono NVARCHAR(50) NOT NULL,
	Total MONEY NOT NULL
)
GO

CREATE TABLE LibrosPorCompra (
	IDLibroPorCompra INT PRIMARY KEY IDENTITY (1,1) NOT NULL,
	IDCompra INT NOT NULL FOREIGN KEY REFERENCES Compras(IDCompra),
	IDLibro INT NOT NULL FOREIGN KEY REFERENCES Libros(IDLibro),
	Cantidad INT NOT NULL DEFAULT 1,
	PrecioUnitario MONEY NOT NULL,
	Subtotal AS (Cantidad * PrecioUnitario) PERSISTED,
	CONSTRAINT CHK_Cantidad CHECK (Cantidad > 0)
)
GO

CREATE TABLE Devoluciones (
	IDDevolucion INT PRIMARY KEY IDENTITY (1,1) NOT NULL,
	IDCliente INT NOT NULL FOREIGN KEY REFERENCES Clientes(IDCliente),
	IDCompra INT NOT NULL FOREIGN KEY REFERENCES Compras(IDCompra),
	IDLibro INT NOT NULL FOREIGN KEY REFERENCES Libros(IDLibro),
	Descripcion NVARCHAR(300) NOT NULL,
	FechaDevolucion DATETIME NOT NULL
)
GO