CREATE DATABASE TPCLibreriaUTN

GO
USE TPCLibreriaUTN
GO

CREATE TABLE Autores (
	IDAutor INT PRIMARY KEY IDENTITY (1,1) NOT NULL,
	Nombre NVARCHAR(50) NOT NULL,
	Apellido NVARCHAR(50) NOT NULL
)
GO

CREATE TABLE Editoriales (
	IDEditorial INT PRIMARY KEY IDENTITY (1,1) NOT NULL,
	Nombre NVARCHAR(50) NOT NULL
)
GO

CREATE TABLE Generos (
	IDGenero INT PRIMARY KEY IDENTITY (1,1) NOT NULL,
	Nombre NVARCHAR(50) NOT NULL
)
GO

CREATE TABLE Sucursales (
	IDSucursal INT PRIMARY KEY IDENTITY (1,1) NOT NULL,
	Nombre NVARCHAR(50) NOT NULL,
	Direccion NVARCHAR(50) NOT NULL
)
GO

CREATE TABLE Usuarios (
	IDUsuario INT PRIMARY KEY IDENTITY (1,1) NOT NULL,
	Mail NVARCHAR(50) NOT NULL,
	Clave NVARCHAR(50) NOT NULL,
	TipoUsuario INT NOT NULL,
	Eliminado BIT NOT NULL DEFAULT 0
)
GO

CREATE TABLE Clientes (
	IDCliente INT PRIMARY KEY IDENTITY (1,1) NOT NULL,
	IDUsuario INT NOT NULL FOREIGN KEY REFERENCES Usuarios(IDUsuario),
	DNI INT NOT NULL,
	Nombre NVARCHAR(50) NOT NULL,
	Apellido NVARCHAR(50) NOT NULL,
	Telefono INT NOT NULL
)
GO

CREATE TABLE Empleados (
	IDEmpleado INT PRIMARY KEY IDENTITY (1,1) NOT NULL,
	IDUsuario INT NOT NULL FOREIGN KEY REFERENCES Usuarios(IDUsuario),
	Nombre NVARCHAR(50) NOT NULL,
	Apellido NVARCHAR(50) NOT NULL
)
GO

CREATE TABLE Libros (
	IDLibro INT PRIMARY KEY IDENTITY (1,1) NOT NULL,
	IDAutor INT NOT NULL FOREIGN KEY REFERENCES Autores(IDAutor),
	IDGenero INT NOT NULL FOREIGN KEY REFERENCES Generos(IDGenero),
	IDEditorial INT NOT NULL FOREIGN KEY REFERENCES Editoriales(IDEditorial),
	IDSucursal INT NOT NULL FOREIGN KEY REFERENCES Sucursales(IDSucursal),
	Titulo NVARCHAR(50) NOT NULL,
	Descripcion NVARCHAR(500) NOT NULL,
	FechaDePublicacion DATETIME NOT NULL,
	Precio MONEY NOT NULL,
	Portada IMAGE NOT NULL,
	Stock INT NOT NULL DEFAULT 0
)
GO

CREATE TABLE Deseados (
	IDDeseado INT PRIMARY KEY IDENTITY (1,1) NOT NULL,
	IDCliente INT NOT NULL FOREIGN KEY REFERENCES Clientes(IDCliente),
	IDLibro INT NOT NULL FOREIGN KEY REFERENCES Libros(IDLibro)
)
GO

CREATE TABLE Carrito (
	IDCarrito INT PRIMARY KEY IDENTITY (1,1) NOT NULL, 
	IDCliente INT NOT NULL FOREIGN KEY REFERENCES Clientes(IDCliente),
	IDLibro INT NOT NULL FOREIGN KEY REFERENCES Libros(IDLibro)
)
GO

CREATE TABLE StockPorSucursales (
	IDStock INT PRIMARY KEY IDENTITY (1,1) NOT NULL,
	IDLibro INT NOT NULL FOREIGN KEY REFERENCES Libros(IDLibro),
	Cantidad INT NOT NULL
)
GO

CREATE TABLE Compras (
	IDCompra INT PRIMARY KEY IDENTITY (1,1) NOT NULL,
	IDCliente INT NOT NULL FOREIGN KEY REFERENCES Clientes(IDCliente),
	IDLibro INT NOT NULL FOREIGN KEY REFERENCES Libros(IDLibro),
	IDSucursal INT NOT NULL FOREIGN KEY REFERENCES Sucursales(IDSucursal)
)
GO

CREATE TABLE Devoluciones (
	IDDevolucion INT PRIMARY KEY IDENTITY (1,1) NOT NULL,
	IDCliente INT NOT NULL FOREIGN KEY REFERENCES Clientes(IDCliente),
	IDCompra INT NOT NULL FOREIGN KEY REFERENCES Compras(IDCompra),
	IDLibro INT NOT NULL FOREIGN KEY REFERENCES Libros(IDLibro),
	Descripcion NVARCHAR(300) NOT NULL,
	FechaDevolucion DATETIME NOT NULL
)
GO